version: "3.8"
services:
  backend:
    image: maven:3-openjdk-11
    volumes:
      - .:/usr/src/rest-api:rw
    working_dir: /usr/src/rest-api
    command: mvn spring-boot:run
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      POSTGRES_DB: rest-api
      POSTGRES_USER: rest-api
      POSTGRES_PASSWORD: asdasd

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: rest-api
      POSTGRES_USER: rest-api
      POSTGRES_PASSWORD: asdasd
    ports:
      - 54322:5432

  zookeeper:
    image: "zookeeper:3.4"
    hostname: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - 9100:9000
    environment:
      - KAFKA_BROKERCONNECT=kafka:29092
      - JVM_OPTS=-Xms32M -Xmx64M
    depends_on:
      - kafka

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
