app:
  kafka:
    topics:
      user-creation:
        name: user-creation
spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: default
      auto-offset-reset: earliest

  mail:
    host: mailhog
    port: 1025
    debug: true
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
    addresses:
      from: no-reply@java-rest-api.com
      replyTo: no-reply@java-rest-api.com

  thymeleaf:
    check-template-location: true
    prefix: 'classpath:/templates/'
    suffix: .html
    mode: HTML5
    encoding: UTF-8